export interface SeedReadingQuestion {
  section: number; // Passage 1, 2, 3
  topic: string;
  questionType: string;
  difficulty: 'easy' | 'medium' | 'hard';
  targetBand: number;
  passageTitle: string;
  passageContent: string;
  passageContentVi: string;
  instruction: string;
  instructionVi: string;
  questionText: string;
  questionTextVi: string;
  options?: Array<{ id: string; text: string; textVi?: string }>;
  correctAnswer: string | string[];
  explanationEn: string;
  explanationVi: string;
  evidenceQuote: string;
  distractorExplanations?: Record<string, { en: string; vi: string }>;
}

const PASSAGE_1_TITLE = 'The Resurgence of Urban Vertical Farming';
const PASSAGE_1_CONTENT = `[Paragraph A] By the year 2050, the global human population is projected to exceed nine billion people, with nearly seventy percent residing in metropolitan urban centers. Meeting the nutritional demands of this burgeoning populace will necessitate a estimated sixty percent increase in arable food production. However, traditional outdoor agriculture is already approaching ecological boundaries: topsoil degradation, freshwater scarcity, and changing climatic patterns present formidable constraints on conventional farming acreage. In response to these pressing crises, agricultural scientists and urban architects are pioneering vertical farming—an innovative method of cultivating crops in stacked vertical layers, typically integrated within repurposed skyscrapers, shipping containers, or underground facilities.

[Paragraph B] Unlike conventional field agriculture, which relies on unpredictable weather and natural soil compositions, vertical farms operate within tightly controlled indoor environments. Utilizing sophisticated closed-loop hydroponic and aeroponic systems, plant roots are nourished via mineral-rich water solutions or nutrient mist rather than organic dirt. Because the ambient environment is sealed, these facilities consume up to ninety-five percent less freshwater than traditional irrigation systems, as evaporated moisture is continuously captured and recirculated. Furthermore, artificial LED lighting arrays can be calibrated to emit precise light wavelengths optimal for photosynthesis, enabling year-round harvest cycles irrespective of external seasonal changes.

[Paragraph C] The ecological dividends of indoor cultivation are substantial. Because crops are grown inside sterile enclosures, the need for chemical herbicides and synthetic pesticides is virtually eliminated. This not only prevents toxic runoff from polluting surrounding river basins and groundwater tables, but also yields produce that is completely organic and safe for consumption. Moreover, locating food production directly adjacent to consumer hubs dramatically reduces food miles—the distance produce must travel from rural farm to urban dinner plate—thereby slashing transportation emissions and post-harvest spoilage rates.

[Paragraph D] Despite these compelling environmental advantages, vertical farming faces significant socioeconomic hurdles, predominantly centered around capital expenditure and energy consumption. Erecting high-tech multi-story growing centers requires colossal upfront financial investments in specialized automated infrastructure, automated robotic harvesters, and high-intensity LED systems. Operating these artificial light arrays and climate-control fans twenty-four hours a day demands enormous amounts of electrical energy. Critics rightly note that unless vertical facilities are powered entirely by renewable energy such as solar panels or wind turbines, their overall carbon footprint may inadvertently surpass that of traditional soil-based farms.

[Paragraph E] To overcome these commercial bottlenecks, engineers are increasingly turning to advanced automation, machine learning algorithms, and genetic optimization. AI-driven multispectral sensors can now monitor individual leaf pigmentation and moisture levels in real time, administering micro-doses of nutrients with pinpoint precision. Simultaneously, agricultural botanists are developing dwarf crop varieties specifically tailored for compact vertical racks. While leafy greens and herbs currently dominate commercial production due to their short growth cycles and high profit margins, ongoing breakthroughs may soon expand indoor feasibility to caloric staple grains such as wheat and rice.`;

const PASSAGE_1_CONTENT_VI = `[Đoạn A] Đến năm 2050, dân số toàn cầu dự kiến sẽ vượt quá 9 tỷ người, với gần 70% cư trú tại các đô thị. Đáp ứng nhu cầu dinh dưỡng này đòi hỏi tăng 60% sản lượng lương thực. Tuy nhiên, nông nghiệp truyền thống đang đối mặt với xói mòn đất, khan hiếm nước và biến đổi khí hậu. Để giải quyết, các nhà khoa học và kiến trúc sư đang tiên phong phát triển nông nghiệp thẳng đứng (vertical farming)—trồng cây theo các tầng xếp chồng lên nhau trong các tòa nhà chọc trời, container hoặc cơ sở ngầm.

[Đoạn B] Khác với nông nghiệp truyền thống phụ thuộc thời tiết, các trang trại thẳng đứng hoạt động trong môi trường khép kín. Bằng hệ thống thủy canh và khí canh, rễ cây được nuôi bằng dung dịch khoáng hoặc sương dinh dưỡng thay vì đất. Nhờ môi trường kín, các trang trại này tiết kiệm tới 95% nước vì độ ẩm bay hơi được thu gom và tái tuần hoàn liên tục. Hệ thống đèn LED được điều chỉnh bước sóng tối ưu giúp thu hoạch quanh năm.

[Đoạn C] Lợi ích sinh thái rất lớn: không cần thuốc diệt cỏ và trừ sâu hóa học, tránh ô nhiễm nguồn nước và tạo ra nông sản hữu cơ sạch. Hơn nữa, việc sản xuất ngay cạnh nơi tiêu thụ giúp giảm đáng kể "food miles" (quãng đường vận chuyển), cắt giảm khí thải và tỷ lệ hư hỏng sau thu hoạch.

[Đoạn D] Mặc dù vậy, nông nghiệp thẳng đứng gặp trở ngại lớn về vốn đầu tư và năng lượng. Xây dựng các tòa nhà công nghệ cao đòi hỏi vốn khổng lồ cho hạ tầng tự động hóa và đèn LED. Vận hành hệ thống chiếu sáng và làm mát 24/7 tiêu tốn rất nhiều điện năng. Nếu không dùng năng lượng tái tạo, lượng phát thải carbon có thể vượt cả nông nghiệp truyền thống.

[Đoạn E] Để vượt qua nút thắt, các kỹ sư đang ứng dụng tự động hóa, AI và tối ưu hóa gen. Cảm biến AI theo dõi từng lá cây để cung cấp dinh dưỡng chính xác. Các nhà thực vật học đang lai tạo các giống cây lùn phù hợp với giá đỡ thẳng đứng. Dù hiện tại rau xanh và thảo mộc chiếm ưu thế do vòng đời ngắn và lợi nhuận cao, các đột phá có thể sớm mở rộng sang các cây lương thực chính như lúa mì và gạo.`;

// PASSAGE 2
const PASSAGE_2_TITLE = 'Artificial Intelligence in Higher Education: Pedagogy vs Automation';
const PASSAGE_2_CONTENT = `[Paragraph A] The rapid proliferation of large language models and generative artificial intelligence tools has ignited an unprecedented debate across universities worldwide. Academic administrators and lecturers find themselves standing at a crossroads: should generative AI be embraced as an empowering cognitive scaffold, or banned as an existential threat to academic integrity? While initial institutional reactions leaned heavily toward prohibitive policies and plagiarism detection software, educators are coming to recognize that banning ubiquitous AI tools is neither pragmatic nor pedagogically sound.

[Paragraph B] Proponents of AI integration highlight its capacity to democratize personalized education. In traditional lecture halls with student-to-faculty ratios exceeding one hundred to one, delivering tailored feedback to individual learners is practically impossible. Adaptive AI tutoring systems, conversely, can analyze a student\'s writing style, diagnose specific conceptual misunderstandings, and generate bespoke supplementary exercises at any hour of the day. For non-native English speakers in particular, generative tools can act as round-the-clock language coaches, clarifying complex disciplinary jargon and explaining syntactic structures in their mother tongue.

[Paragraph C] Nonetheless, severe pedagogical concerns persist regarding cognitive offloading—the phenomenon where learners delegate critical analysis and problem-solving to automated algorithms. Cognitive scientists warn that if students rely on AI to synthesize research papers and draft argumentative essays, the essential neurological pathways responsible for independent reasoning, deep reading, and creative synthesis may atrophy. When the struggle of formulating an original thesis is bypassed, the depth of conceptual mastery is inevitably compromised.

[Paragraph D] Furthermore, academic integrity issues extend beyond straightforward essay plagiarism. Generative models frequently generate hallucinations—factually erroneous assertions presented with authoritative confidence—accompanied by fabricated citations. Undergraduate students lacking advanced domain expertise often fail to detect these plausible falsehoods, uncritically incorporating fictitious data into their academic dissertations. Consequently, several leading institutions have restructured assessments, shifting from unsupervised take-home essays toward oral defenses, in-class bluebook examinations, and collaborative project portfolios.

[Paragraph E] Ultimately, the consensus among forward-looking educational theorists is that higher education must shift from testing static knowledge retrieval to fostering AI literacy and ethical discernment. Rather than asking students to write essays that machines can replicate in seconds, curricula should train students to formulate incisive prompts, critically interrogate AI-generated outputs, cross-reference empirical sources, and synthesize human ethical judgment with algorithmic efficiency. In this evolving paradigm, AI is not a substitute for human intellect, but an intellectual catalyst.`;

const PASSAGE_2_CONTENT_VI = `[Đoạn A] Sự bùng nổ của mô hình ngôn ngữ lớn và AI tạo sinh đã châm ngòi cho cuộc tranh luận chưa từng có tại các trường đại học. Các nhà quản lý và giảng viên đứng trước ngã rẽ: nên đón nhận AI như một công cụ hỗ trợ tư duy hay cấm nó như một mối đe dọa với liêm chính học thuật? Sau phản ứng cấm đoán ban đầu, các nhà giáo dục nhận ra rằng việc cấm đoán công cụ phổ biến này là không thực tế.

[Đoạn B] Những người ủng hộ nhấn mạnh khả năng cá nhân hóa giáo dục. Trong các giảng đường lớn với tỷ lệ sinh viên trên giảng viên vượt 100:1, việc cung cấp phản hồi riêng là bất khả thi. Ngược lại, hệ thống gia sư AI có thể chẩn đoán hiểu lầm kiến thức và tạo bài tập bổ trợ bất cứ lúc nào. Đối với sinh viên không nói tiếng Anh bản xứ, AI đóng vai trò như huấn luyện viên ngôn ngữ 24/7.

[Đoạn C] Tuy nhiên, những lo ngại sâu sắc vẫn tồn tại về hiện tượng "cognitive offloading" (suy giảm nhận thức do phụ thuộc máy móc). Các nhà khoa học cảnh báo nếu sinh viên ỷ lại vào AI để tóm tắt bài báo và viết luận, các kỹ năng tư duy độc lập và đọc sâu có thể bị thui chột. Khi bỏ qua quá trình tự vật lộn để hình thành luận điểm, sự hiểu biết sâu sắc sẽ bị tổn hại.

[Đoạn D] Ngoài ra, AI thường tạo ra các "ảo giác" (hallucinations)—những nhận định sai sự thật nhưng được trình bày rất tự tin cùng các trích dẫn giả mạo. Sinh viên chưa có chuyên môn sâu thường không phát hiện được và đưa dữ liệu giả vào bài làm. Vì vậy, nhiều trường đã chuyển sang thi vấn đáp, thi viết trực tiếp tại lớp và làm dự án nhóm.

[Đoạn E] Cuối cùng, lý thuyết giáo dục tiến bộ cho rằng các trường cần chuyển từ kiểm tra ghi nhớ sang đào tạo năng lực hiểu biết về AI (AI literacy). Thay vì yêu cầu viết bài luận mà máy móc làm được trong vài giây, chương trình học nên rèn luyện kỹ năng đặt câu hỏi, phản biện kết quả của AI và kết hợp đánh giá đạo đức của con người với hiệu quả của thuật toán.`;

// PASSAGE 3
const PASSAGE_3_TITLE = 'The Biomimicry Revolution in Architecture';
const PASSAGE_3_CONTENT = `[Paragraph A] For millions of years, biological organisms have evolved ingenious solutions to survive harsh environmental pressures, optimizing thermal regulation, structural resilience, and resource efficiency without producing non-biodegradable waste. In the architectural sphere, this wisdom has catalyzed biomimicry—the practice of emulating nature’s time-tested designs and ecological strategies to engineer sustainable, climate-resilient human habitats. Rather than merely adorning buildings with floral motifs, biomimetic architects analyze the underlying functional principles of living organisms to solve complex structural and thermal engineering dilemmas.

[Paragraph B] One of the most famous triumphs of biomimetic engineering is the Eastgate Centre, a massive shopping and office complex in Harare, Zimbabwe, designed by architect Mick Pearce. Conventional commercial buildings in sub-Saharan Africa consume colossal quantities of electricity to operate mechanical air-conditioning units. Pearce instead drew inspiration from the self-cooling mounds built by indigenous termites. Despite external temperatures fluctuating between 35°C during the day and 10°C at night, termite mounds maintain a steady interior temperature of 31°C through a network of convection vents. Pearce replicated this mechanism in the Eastgate Centre using passive airflow shafts and concrete thermal mass, reducing the building's energy consumption by ninety percent compared to adjacent traditional structures.

[Paragraph C] Another biological marvel inspiring structural engineers is the glass sponge (Euplectella aspergillum), an organism that thrives in the crushing pressures of the deep sea. The sponge constructs an intricate cylindrical skeleton composed of crisscrossed silica struts, stabilized by internal diagonal braces. Structural analysis reveals that this lattice framework resists buckling and shear forces far more effectively than traditional human-engineered trusses of equivalent weight. Modern civil engineers are now translating this hexagonal lattice pattern into high-rise skyscraper frames, achieving greater earthquake resilience while utilizing up to twenty percent less structural steel.

[Paragraph D] Biomimicry is also revolutionizing exterior materials through surface micro-textures. The leaves of the sacred lotus flower remain pristine despite growing in muddy waters because microscopic nanoscale wax crystals cause water droplets to bead into spheres, collecting dirt particles as they roll away—a phenomenon termed the "lotus effect." Chemical engineers have synthesized exterior building paints and glass coatings that replicate this hydrophobic surface roughness. Buildings coated with these biomimetic finishes are self-cleaning when exposed to rainfall, eliminating the hazardous labor and high maintenance expenses associated with manual window washing.

[Paragraph E] Looking toward the future, architects are expanding beyond single-organism mimicry toward whole-ecosystem emulation. Rather than operating as linear systems that ingest raw resources and expel toxic refuse, next-generation urban developments are modeled after mature forests. In these closed-loop architectural ecologies, wastewater from residential towers is purified through biological reed beds, waste heat from commercial servers warms municipal greenhouses, and building materials are entirely compostable or infinitely recyclable. Through biomimicry, human civilization is beginning to reconcile the built environment with the natural biosphere.`;

const PASSAGE_3_CONTENT_VI = `[Đoạn A] Qua hàng triệu năm, các sinh vật sống đã tiến hóa để thích nghi với môi trường khắc nghiệt, tối ưu hóa khả năng điều hòa nhiệt độ và độ bền mà không tạo ra rác thải không thể phân hủy. Trong kiến trúc, điều này thúc đẩy xu hướng "biomimicry" (mô phỏng sinh học)—ứng dụng thiết kế của tự nhiên vào xây dựng bền vững. Các kiến trúc sư không chỉ vẽ họa tiết thiên nhiên, mà phân tích các nguyên lý chức năng của sinh vật để giải quyết các bài toán kỹ thuật phức tạp.

[Đoạn B] Một ví dụ tiêu biểu là tòa nhà Eastgate Centre tại Harare, Zimbabwe do Mick Pearce thiết kế. Thay vì dùng điều hòa tiêu tốn nhiều điện, Pearce lấy cảm hứng từ tổ mối. Dù nhiệt độ bên ngoài dao động từ 35°C ban ngày xuống 10°C ban đêm, tổ mối vẫn giữ nhiệt độ ổn định 31°C nhờ hệ thống lỗ thông gió đối lưu. Pearce đã áp dụng cơ chế này vào Eastgate Centre, giúp giảm 90% lượng điện tiêu thụ so với các tòa nhà thông thường lân cận.

[Đoạn C] Một loài sinh vật khác là bọt biển thủy tinh (Euplectella aspergillum) sống ở độ sâu lớn dưới đáy biển. Bộ xương hình trụ của nó gồm các thanh silica đan chéo giúp chịu được áp lực cực lớn mà nhẹ hơn cấu trúc thông thường. Các kỹ sư đang ứng dụng cấu trúc lưới này vào khung các tòa nhà chọc trời, giúp chống chịu động đất tốt hơn mà tiết kiệm tới 20% thép xây dựng.

[Đoạn D] Mô phỏng sinh học cũng tạo ra các vật liệu bề mặt mới. Lá sen luôn sạch sẽ dù mọc trong bùn nhờ các tinh thể sáp kích thước nano làm giọt nước vo tròn và cuốn trôi bụi bẩn ("hiệu ứng lá sen"). Các nhà khoa học đã chế tạo sơn tường và kính mô phỏng bề mặt này, giúp các tòa nhà tự làm sạch khi trời mưa, tiết kiệm chi phí lau dọn.

[Đoạn E] Trong tương lai, các kiến trúc sư hướng tới mô phỏng toàn bộ hệ sinh thái khép kín giống như một khu rừng tự nhiên. Nước thải được xử lý bằng bãi lau sậy sinh học, nhiệt thừa từ máy chủ được dùng sưởi ấm nhà kính và vật liệu xây dựng có thể tái chế vô hạn.`;

export const READING_SEED_DATA: SeedReadingQuestion[] = [
  // PASSAGE 1: 10 Questions
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'true_false_not_given',
    difficulty: 'easy',
    targetBand: 6.0,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Do the following statements agree with the information given in the text? Write TRUE, FALSE, or NOT GIVEN.',
    instructionVi: 'Các nhận định sau có đúng với thông tin trong bài không? Điền TRUE, FALSE hoặc NOT GIVEN.',
    questionText: 'By 2050, more than half of the world\'s population will live in cities.',
    questionTextVi: 'Đến năm 2050, hơn một nửa dân số thế giới sẽ sống tại các thành phố.',
    correctAnswer: 'TRUE',
    explanationEn: 'Paragraph A states that nearly seventy percent of the projected population will reside in metropolitan urban centers. Seventy percent is indeed "more than half".',
    explanationVi: 'Đoạn A khẳng định: "with nearly seventy percent residing in metropolitan urban centers" (gần 70% sống ở trung tâm đô thị). 70% lớn hơn một nửa -> TRUE.',
    evidenceQuote: 'with nearly seventy percent residing in metropolitan urban centers.',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'true_false_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Write TRUE, FALSE, or NOT GIVEN.',
    instructionVi: 'Điền TRUE, FALSE hoặc NOT GIVEN.',
    questionText: 'Vertical farms use significantly more water than conventional open-field farms.',
    questionTextVi: 'Trang trại thẳng đứng sử dụng nhiều nước hơn đáng kể so với nông nghiệp ngoài đồng truyền thống.',
    correctAnswer: 'FALSE',
    explanationEn: 'Paragraph B explicitly notes that vertical facilities consume "up to ninety-five percent less freshwater than traditional irrigation systems".',
    explanationVi: 'Đoạn B khẳng định các cơ sở này "consume up to ninety-five percent less freshwater" (tiết kiệm tới 95% nước so với tưới tiêu truyền thống), chứ không phải dùng nhiều hơn -> FALSE.',
    evidenceQuote: 'these facilities consume up to ninety-five percent less freshwater than traditional irrigation systems',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'true_false_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Write TRUE, FALSE, or NOT GIVEN.',
    instructionVi: 'Điền TRUE, FALSE hoặc NOT GIVEN.',
    questionText: 'The Japanese government provides subsidies for businesses investing in vertical farms.',
    questionTextVi: 'Chính phủ Nhật Bản cung cấp các khoản trợ cấp cho các doanh nghiệp đầu tư vào trang trại thẳng đứng.',
    correctAnswer: 'NOT GIVEN',
    explanationEn: 'The passage discusses capital costs and investments in Paragraph D, but makes no mention of the Japanese government or specific national subsidies.',
    explanationVi: 'Bài đọc đề cập đến chi phí đầu tư ở Đoạn D nhưng hoàn toàn không nhắc tới chính phủ Nhật Bản hay chính sách trợ cấp của nước này -> NOT GIVEN.',
    evidenceQuote: '',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'summary_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.',
    instructionVi: 'Hoàn thành đoạn tóm tắt dưới đây. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc cho mỗi câu trả lời.',
    questionText: 'In vertical farms, crops are grown inside sterile enclosures, meaning that chemical __________ and synthetic pesticides are completely unnecessary.',
    questionTextVi: 'Trong các trang trại thẳng đứng, cây trồng được nuôi dưỡng trong môi trường vô trùng, đồng nghĩa với việc __________ hóa học và thuốc trừ sâu tổng hợp hoàn toàn không cần thiết.',
    correctAnswer: 'herbicides',
    explanationEn: 'Paragraph C states: "the need for chemical herbicides and synthetic pesticides is virtually eliminated."',
    explanationVi: 'Đoạn C nêu rõ: "the need for chemical herbicides and synthetic pesticides is virtually eliminated" -> Điền "herbicides".',
    evidenceQuote: 'the need for chemical herbicides and synthetic pesticides is virtually eliminated.',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'summary_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage for each answer.',
    instructionVi: 'Hoàn thành đoạn tóm tắt dưới đây. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc cho mỗi câu trả lời.',
    questionText: 'Locating food production near consumers helps decrease __________, which in turn cuts transport emissions.',
    questionTextVi: 'Đặt các cơ sở sản xuất lương thực gần người tiêu dùng giúp giảm bớt __________, từ đó cắt giảm khí thải vận tải.',
    correctAnswer: 'food miles',
    explanationEn: 'Paragraph C mentions: "dramatically reduces food miles—the distance produce must travel from rural farm to urban dinner plate".',
    explanationVi: 'Đoạn C chỉ ra: "dramatically reduces food miles—the distance produce must travel..." -> Điền "food miles".',
    evidenceQuote: 'dramatically reduces food miles—the distance produce must travel from rural farm to urban dinner plate',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'mcq',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Choose the correct letter, A, B, C, or D.',
    instructionVi: 'Chọn chữ cái đúng, A, B, C hoặc D.',
    questionText: 'According to Paragraph D, what is a primary criticism of vertical farming?',
    questionTextVi: 'Theo Đoạn D, lời chỉ trích chính đối với nông nghiệp thẳng đứng là gì?',
    options: [
      { id: 'A', text: 'It fails to produce nutrient-rich vegetables.', textVi: 'Nó không tạo ra được rau củ giàu dinh dưỡng.' },
      { id: 'B', text: 'It can cause excessive soil degradation.', textVi: 'Nó có thể gây ra xói mòn đất quá mức.' },
      { id: 'C', text: 'Its heavy electricity consumption could negate its environmental benefits.', textVi: 'Lượng điện tiêu thụ khổng lồ có thể triệt tiêu các lợi ích môi trường của nó.' },
      { id: 'D', text: 'It requires far too much manual human labor.', textVi: 'Nó đòi hỏi quá nhiều lao động chân tay của con người.' },
    ],
    correctAnswer: 'C',
    explanationEn: 'Paragraph D warns that running lights and fans around the clock demands enormous energy, and without renewables, the carbon footprint may surpass traditional farms.',
    explanationVi: 'Đoạn D nhấn mạnh: "unless vertical facilities are powered entirely by renewable energy... their overall carbon footprint may inadvertently surpass that of traditional soil-based farms" -> Chọn C.',
    evidenceQuote: 'unless vertical facilities are powered entirely by renewable energy... their overall carbon footprint may inadvertently surpass that of traditional soil-based farms.',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'matching_headings',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Choose the correct heading for Paragraph B from the list of headings below.',
    instructionVi: 'Chọn tiêu đề đúng cho Đoạn B từ danh sách tiêu đề dưới đây.',
    questionText: 'Paragraph B heading: __________',
    questionTextVi: 'Tiêu đề Đoạn B: __________',
    options: [
      { id: 'i', text: 'Controlled mechanisms and water conservation techniques', textVi: 'Các cơ chế kiểm soát và kỹ thuật bảo tồn nước' },
      { id: 'ii', text: 'The insurmountable financial barriers of urban architecture', textVi: 'Những rào cản tài chính không thể vượt qua của kiến trúc đô thị' },
      { id: 'iii', text: 'The impending crisis of global population growth', textVi: 'Cuộc khủng hoảng sắp tới của sự gia tăng dân số toàn cầu' },
      { id: 'iv', text: 'Technological innovations expanding crop variety', textVi: 'Các đổi mới công nghệ mở rộng chủng loại cây trồng' },
    ],
    correctAnswer: 'i',
    explanationEn: 'Paragraph B describes the controlled indoor environment, closed-loop hydroponics, 95% water savings, and LED lighting.',
    explanationVi: 'Đoạn B tập trung mô tả môi trường kiểm soát khép kín, hệ thống thủy canh/khí canh và khả năng tiết kiệm 95% nước -> Tiêu đề (i).',
    evidenceQuote: 'vertical farms operate within tightly controlled indoor environments. Utilizing sophisticated closed-loop hydroponic and aeroponic systems',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'matching_headings',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Choose the correct heading for Paragraph D from the list of headings below.',
    instructionVi: 'Chọn tiêu đề đúng cho Đoạn D từ danh sách tiêu đề dưới đây.',
    questionText: 'Paragraph D heading: __________',
    questionTextVi: 'Tiêu đề Đoạn D: __________',
    options: [
      { id: 'i', text: 'High financial expenditure and intense energy demands', textVi: 'Chi phí tài chính cao và nhu cầu năng lượng lớn' },
      { id: 'ii', text: 'Eliminating the threat of chemical runoff', textVi: 'Loại bỏ mối đe dọa từ nước thải hóa chất' },
      { id: 'iii', text: 'The genetic alteration of staple grains', textVi: 'Biến đổi gen ở các loại cây lương thực chủ lực' },
      { id: 'iv', text: 'History of early skyscraper agriculture', textVi: 'Lịch sử nông nghiệp trên các tòa nhà chọc trời thời kỳ đầu' },
    ],
    correctAnswer: 'i',
    explanationEn: 'Paragraph D focuses directly on capital costs, multi-story infrastructure investments, and massive electricity consumption.',
    explanationVi: 'Đoạn D phân tích chi phí vốn ban đầu khổng lồ (capital expenditure) và mức độ tiêu thụ điện năng lớn (electrical energy demand) -> Tiêu đề (i).',
    evidenceQuote: 'vertical farming faces significant socioeconomic hurdles, predominantly centered around capital expenditure and energy consumption.',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'sentence_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Complete the sentence. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành câu. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'Botanists are currently engineering __________ crops to better fit within compact vertical shelving.',
    questionTextVi: 'Các nhà thực vật học hiện đang lai tạo các loại cây trồng __________ để vừa vặn hơn với các giá đỡ thẳng đứng nhỏ gọn.',
    correctAnswer: 'dwarf crop',
    explanationEn: 'Paragraph E states: "agricultural botanists are developing dwarf crop varieties specifically tailored for compact vertical racks."',
    explanationVi: 'Đoạn E chỉ ra: "developing dwarf crop varieties specifically tailored for compact vertical racks" -> Điền "dwarf crop".',
    evidenceQuote: 'developing dwarf crop varieties specifically tailored for compact vertical racks.',
  },
  {
    section: 1,
    topic: 'Urban Vertical Farming',
    questionType: 'sentence_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_1_TITLE,
    passageContent: PASSAGE_1_CONTENT,
    passageContentVi: PASSAGE_1_CONTENT_VI,
    instruction: 'Complete the sentence. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành câu. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'Sensors driven by __________ can evaluate foliage coloration and apply precise micro-doses of nutrients.',
    questionTextVi: 'Các cảm biến điều khiển bởi __________ có thể đánh giá màu sắc tán lá và cung cấp vi liều dinh dưỡng chính xác.',
    correctAnswer: 'AI',
    explanationEn: 'Paragraph E mentions: "AI-driven multispectral sensors can now monitor individual leaf pigmentation".',
    explanationVi: 'Đoạn E nêu rõ: "AI-driven multispectral sensors can now monitor individual leaf pigmentation..." -> Điền "AI".',
    evidenceQuote: 'AI-driven multispectral sensors can now monitor individual leaf pigmentation and moisture levels in real time',
  },

  // PASSAGE 2: 10 Questions
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'yes_no_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Do the following statements agree with the claims of the writer? Write YES, NO, or NOT GIVEN.',
    instructionVi: 'Các nhận định sau có trùng khớp với quan điểm của tác giả không? Điền YES, NO hoặc NOT GIVEN.',
    questionText: 'University administrators universally welcomed generative AI when it was first introduced.',
    questionTextVi: 'Các nhà quản lý đại học đã đồng loạt hoan nghênh AI tạo sinh khi nó lần đầu xuất hiện.',
    correctAnswer: 'NO',
    explanationEn: 'Paragraph A states that "initial institutional reactions leaned heavily toward prohibitive policies and plagiarism detection software," indicating opposition rather than welcoming.',
    explanationVi: 'Đoạn A nêu phản ứng ban đầu là cấm đoán và dùng phần mềm quét đạo văn ("prohibitive policies and plagiarism detection software"), trái ngược với việc hoan nghênh -> NO.',
    evidenceQuote: 'initial institutional reactions leaned heavily toward prohibitive policies and plagiarism detection software',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'yes_no_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Write YES, NO, or NOT GIVEN.',
    instructionVi: 'Điền YES, NO hoặc NOT GIVEN.',
    questionText: 'AI tools can provide personalized support to learners who speak English as a second language.',
    questionTextVi: 'Các công cụ AI có thể cung cấp hỗ trợ cá nhân hóa cho người học tiếng Anh như ngôn ngữ thứ hai.',
    correctAnswer: 'YES',
    explanationEn: 'Paragraph B explicitly states that for non-native English speakers, tools can act as round-the-clock coaches explaining jargon and syntax.',
    explanationVi: 'Đoạn B khẳng định: "For non-native English speakers in particular, generative tools can act as round-the-clock language coaches..." -> YES.',
    evidenceQuote: 'For non-native English speakers in particular, generative tools can act as round-the-clock language coaches',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'yes_no_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Write YES, NO, or NOT GIVEN.',
    instructionVi: 'Điền YES, NO hoặc NOT GIVEN.',
    questionText: 'Commercial AI tutoring platforms are significantly more expensive than hiring private human tutors.',
    questionTextVi: 'Các nền tảng gia sư AI thương mại đắt hơn đáng kể so với việc thuê gia sư con người riêng.',
    correctAnswer: 'NOT GIVEN',
    explanationEn: 'The passage discusses the benefits of AI tutoring in Paragraph B, but makes no price comparison to private human tutors.',
    explanationVi: 'Bài đọc không hề so sánh chi phí giữa gia sư AI và gia sư con người -> NOT GIVEN.',
    evidenceQuote: '',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'mcq',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Choose the correct letter, A, B, C, or D.',
    instructionVi: 'Chọn chữ cái đúng, A, B, C hoặc D.',
    questionText: 'What risk is associated with "cognitive offloading" according to cognitive scientists?',
    questionTextVi: 'Rủi ro nào gắn liền với hiện tượng "suy giảm nhận thức do phụ thuộc máy móc" (cognitive offloading)?',
    options: [
      { id: 'A', text: 'Students will spend excessive time learning prompt syntax.', textVi: 'Sinh viên sẽ mất quá nhiều thời gian để học cú pháp câu lệnh.' },
      { id: 'B', text: 'Crucial neural connections for independent thought and deep reading may weaken.', textVi: 'Các kết nối thần kinh thiết yếu cho tư duy độc lập và đọc sâu có thể bị suy yếu.' },
      { id: 'C', text: 'Universities will permanently close large lecture halls.', textVi: 'Các trường đại học sẽ đóng cửa vĩnh viễn các giảng đường lớn.' },
      { id: 'D', text: 'Computer hardware will experience rapid obsolescence.', textVi: 'Phần cứng máy tính sẽ bị lỗi thời nhanh chóng.' },
    ],
    correctAnswer: 'B',
    explanationEn: 'Paragraph C warns that "the essential neurological pathways responsible for independent reasoning, deep reading, and creative synthesis may atrophy."',
    explanationVi: 'Đoạn C cảnh báo: "the essential neurological pathways responsible for independent reasoning, deep reading, and creative synthesis may atrophy" (các đường dẫn thần kinh cho tư duy độc lập và đọc sâu có thể bị teo đi) -> Chọn B.',
    evidenceQuote: 'the essential neurological pathways responsible for independent reasoning, deep reading, and creative synthesis may atrophy.',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'summary_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Complete the summary. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành đoạn tóm tắt. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'Incorrect statements presented convincingly by AI models are known in academic contexts as __________.',
    questionTextVi: 'Các khẳng định sai lệch được mô hình AI trình bày một cách đầy thuyết phục được gọi là __________ trong bối cảnh học thuật.',
    correctAnswer: 'hallucinations',
    explanationEn: 'Paragraph D identifies "hallucinations—factually erroneous assertions presented with authoritative confidence".',
    explanationVi: 'Đoạn D định nghĩa: "Generative models frequently generate hallucinations—factually erroneous assertions..." -> Điền "hallucinations".',
    evidenceQuote: 'Generative models frequently generate hallucinations—factually erroneous assertions presented with authoritative confidence',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'matching_information',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Which paragraph contains the following information? Write the correct letter, A-E.',
    instructionVi: 'Đoạn văn nào chứa thông tin sau? Viết chữ cái đúng, A-E.',
    questionText: 'A description of alternative assessment methods replacing take-home essays: Paragraph __________',
    questionTextVi: 'Mô tả các phương pháp đánh giá thay thế cho bài luận về nhà: Đoạn __________',
    correctAnswer: 'D',
    explanationEn: 'Paragraph D concludes by describing new assessment formats: "shifting from unsupervised take-home essays toward oral defenses, in-class bluebook examinations, and collaborative project portfolios."',
    explanationVi: 'Đoạn D mô tả sự chuyển đổi từ bài luận về nhà sang thi vấn đáp, thi viết tại lớp và hồ sơ dự án nhóm -> Đoạn D.',
    evidenceQuote: 'shifting from unsupervised take-home essays toward oral defenses, in-class bluebook examinations, and collaborative project portfolios.',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'matching_information',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Which paragraph contains the following information? Write the correct letter, A-E.',
    instructionVi: 'Đoạn văn nào chứa thông tin sau? Viết chữ cái đúng, A-E.',
    questionText: 'An explanation of the proposed shift toward critical questioning and verification skills: Paragraph __________',
    questionTextVi: 'Giải thích về sự chuyển dịch sang kỹ năng đặt câu hỏi phản biện và kiểm chứng: Đoạn __________',
    correctAnswer: 'E',
    explanationEn: 'Paragraph E discusses shifting toward AI literacy, formulating incisive prompts, critically interrogating outputs, and cross-referencing sources.',
    explanationVi: 'Đoạn E nói về việc đào tạo sinh viên kỹ năng đặt câu hỏi sắc bén (incisive prompts), phản biện đầu ra và đối chiếu nguồn thực nghiệm -> Đoạn E.',
    evidenceQuote: 'curricula should train students to formulate incisive prompts, critically interrogate AI-generated outputs, cross-reference empirical sources',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'mcq',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Choose the correct letter, A, B, C, or D.',
    instructionVi: 'Chọn chữ cái đúng, A, B, C hoặc D.',
    questionText: 'What is the overarching conclusion of the author in Paragraph E?',
    questionTextVi: 'Kết luận bao trùm của tác giả ở Đoạn E là gì?',
    options: [
      { id: 'A', text: 'Universities will soon replace human instructors entirely with generative algorithms.', textVi: 'Các trường đại học sẽ sớm thay thế hoàn toàn giảng viên con người bằng các thuật toán tạo sinh.' },
      { id: 'B', text: 'AI should be viewed as an intellectual catalyst rather than a replacement for human thought.', textVi: 'AI nên được xem như chất xúc tác trí tuệ chứ không phải sự thay thế cho tư duy con người.' },
      { id: 'C', text: 'Written examinations will be made obsolete by oral debates.', textVi: 'Các kỳ thi viết sẽ bị loại bỏ bởi các cuộc tranh biện miệng.' },
      { id: 'D', text: 'Plagiarism will cease to exist once AI literacy is formally accredited.', textVi: 'Nạn đạo văn sẽ biến mất một khi năng lực hiểu biết AI được công nhận chính thức.' },
    ],
    correctAnswer: 'B',
    explanationEn: 'Paragraph E concludes: "In this evolving paradigm, AI is not a substitute for human intellect, but an intellectual catalyst."',
    explanationVi: 'Câu cuối cùng của Đoạn E khẳng định: "AI is not a substitute for human intellect, but an intellectual catalyst" -> Chọn B.',
    evidenceQuote: 'In this evolving paradigm, AI is not a substitute for human intellect, but an intellectual catalyst.',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'sentence_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Complete the sentence. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành câu. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'Large lecture halls frequently struggle to deliver tailored support because the student-to-faculty ratio often surpasses __________.',
    questionTextVi: 'Các giảng đường lớn thường gặp khó khăn trong việc hỗ trợ cá nhân hóa vì tỷ lệ sinh viên trên giảng viên thường vượt quá __________.',
    correctAnswer: 'one hundred to one',
    explanationEn: 'Paragraph B mentions: "In traditional lecture halls with student-to-faculty ratios exceeding one hundred to one".',
    explanationVi: 'Đoạn B chỉ ra: "with student-to-faculty ratios exceeding one hundred to one" -> Điền "one hundred to one".',
    evidenceQuote: 'with student-to-faculty ratios exceeding one hundred to one',
  },
  {
    section: 2,
    topic: 'AI in Higher Education',
    questionType: 'sentence_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_2_TITLE,
    passageContent: PASSAGE_2_CONTENT,
    passageContentVi: PASSAGE_2_CONTENT_VI,
    instruction: 'Complete the sentence. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành câu. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'Rather than testing static knowledge recall, universities must prioritize cultivating __________ among students.',
    questionTextVi: 'Thay vì kiểm tra việc ghi nhớ kiến thức tĩnh, các trường đại học phải ưu tiên bồi dưỡng __________ ở sinh viên.',
    correctAnswer: 'AI literacy',
    explanationEn: 'Paragraph E states: "higher education must shift from testing static knowledge retrieval to fostering AI literacy".',
    explanationVi: 'Đoạn E nêu rõ: "shift from testing static knowledge retrieval to fostering AI literacy" -> Điền "AI literacy".',
    evidenceQuote: 'shift from testing static knowledge retrieval to fostering AI literacy and ethical discernment.',
  },

  // PASSAGE 3: 10 Questions
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'true_false_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Do the following statements agree with the information given in the text? Write TRUE, FALSE, or NOT GIVEN.',
    instructionVi: 'Các nhận định sau có đúng với thông tin trong bài không? Điền TRUE, FALSE hoặc NOT GIVEN.',
    questionText: 'The Eastgate Centre in Zimbabwe relies entirely on traditional electric air-conditioning systems.',
    questionTextVi: 'Tòa nhà Eastgate Centre ở Zimbabwe phụ thuộc hoàn toàn vào hệ thống điều hòa không khí truyền thống bằng điện.',
    correctAnswer: 'FALSE',
    explanationEn: 'Paragraph B explains that Mick Pearce bypassed mechanical air-conditioning by emulating termite mounds, cutting energy consumption by 90%.',
    explanationVi: 'Đoạn B nêu rõ Pearce không dùng điều hòa cơ học tiêu tốn điện mà dùng cơ chế thông gió tự nhiên của tổ mối, giảm 90% năng lượng -> FALSE.',
    evidenceQuote: 'Pearce replicated this mechanism in the Eastgate Centre using passive airflow shafts and concrete thermal mass, reducing the building\'s energy consumption by ninety percent',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'true_false_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Write TRUE, FALSE, or NOT GIVEN.',
    instructionVi: 'Điền TRUE, FALSE hoặc NOT GIVEN.',
    questionText: 'Termite mounds maintain a stable interior temperature despite broad outdoor temperature shifts.',
    questionTextVi: 'Tổ mối duy trì nhiệt độ bên trong ổn định bất chấp sự thay đổi lớn của nhiệt độ ngoài trời.',
    correctAnswer: 'TRUE',
    explanationEn: 'Paragraph B states: "Despite external temperatures fluctuating between 35°C during the day and 10°C at night, termite mounds maintain a steady interior temperature of 31°C".',
    explanationVi: 'Đoạn B khẳng định dù nhiệt độ bên ngoài dao động từ 35°C ban ngày xuống 10°C ban đêm, nhiệt độ trong tổ vẫn ổn định ở 31°C -> TRUE.',
    evidenceQuote: 'Despite external temperatures fluctuating between 35°C during the day and 10°C at night, termite mounds maintain a steady interior temperature of 31°C',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'true_false_not_given',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Write TRUE, FALSE, or NOT GIVEN.',
    instructionVi: 'Điền TRUE, FALSE hoặc NOT GIVEN.',
    questionText: 'The glass sponge is found exclusively in shallow tropical coral reefs.',
    questionTextVi: 'Bọt biển thủy tinh chỉ được tìm thấy duy nhất ở các rạn san hô nhiệt đới nông.',
    correctAnswer: 'FALSE',
    explanationEn: 'Paragraph C describes the glass sponge as an organism that "thrives in the crushing pressures of the deep sea", not in shallow reefs.',
    explanationVi: 'Đoạn C mô tả bọt biển thủy tinh sống ở vùng áp suất khổng lồ của biển sâu ("crushing pressures of the deep sea"), không phải rạn san hô nông -> FALSE.',
    evidenceQuote: 'an organism that thrives in the crushing pressures of the deep sea.',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'matching_features',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Match each organism with its architectural innovation. Choose A, B, or C.',
    instructionVi: 'Nối từng sinh vật với ứng dụng đổi mới kiến trúc tương ứng. Chọn A, B hoặc C.',
    questionText: 'The sacred lotus flower: __________',
    questionTextVi: 'Lá sen: __________',
    options: [
      { id: 'A', text: 'Self-cleaning exterior surfaces that shed dirt in rain', textVi: 'Bề mặt tự làm sạch giúp cuốn trôi bụi bẩn khi trời mưa' },
      { id: 'B', text: 'Passive convective cooling without mechanical refrigeration', textVi: 'Làm mát đối lưu thụ động không cần máy lạnh cơ học' },
      { id: 'C', text: 'Hexagonal lattice structure providing earthquake resistance', textVi: 'Cấu trúc lưới lục giác mang lại khả năng chống động đất' },
    ],
    correctAnswer: 'A',
    explanationEn: 'Paragraph D explains that the nanoscale wax crystals on lotus leaves inspired self-cleaning paints and glass coatings.',
    explanationVi: 'Đoạn D mô tả hiệu ứng lá sen tạo cảm hứng cho các lớp sơn và kính tự làm sạch khi trời mưa -> Chọn A.',
    evidenceQuote: 'Buildings coated with these biomimetic finishes are self-cleaning when exposed to rainfall',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'matching_features',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Match each organism with its architectural innovation. Choose A, B, or C.',
    instructionVi: 'Nối từng sinh vật với ứng dụng đổi mới kiến trúc tương ứng. Chọn A, B hoặc C.',
    questionText: 'The glass sponge: __________',
    questionTextVi: 'Bọt biển thủy tinh: __________',
    options: [
      { id: 'A', text: 'Self-cleaning exterior surfaces that shed dirt in rain', textVi: 'Bề mặt tự làm sạch giúp cuốn trôi bụi bẩn khi trời mưa' },
      { id: 'B', text: 'Passive convective cooling without mechanical refrigeration', textVi: 'Làm mát đối lưu thụ động không cần máy lạnh cơ học' },
      { id: 'C', text: 'Hexagonal lattice structure providing earthquake resistance', textVi: 'Cấu trúc lưới lục giác mang lại khả năng chống động đất' },
    ],
    correctAnswer: 'C',
    explanationEn: 'Paragraph C describes how the crisscrossed silica lattice of the glass sponge inspired earthquake-resilient skyscraper frames.',
    explanationVi: 'Đoạn C nêu cấu trúc giàn silica đan chéo của bọt biển thủy tinh được ứng dụng vào khung nhà chọc trời chống động đất -> Chọn C.',
    evidenceQuote: 'translating this hexagonal lattice pattern into high-rise skyscraper frames, achieving greater earthquake resilience',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'matching_features',
    difficulty: 'hard',
    targetBand: 7.0,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Match each organism with its architectural innovation. Choose A, B, or C.',
    instructionVi: 'Nối từng sinh vật với ứng dụng đổi mới kiến trúc tương ứng. Chọn A, B hoặc C.',
    questionText: 'Indigenous termites: __________',
    questionTextVi: 'Loài mối bản địa: __________',
    options: [
      { id: 'A', text: 'Self-cleaning exterior surfaces that shed dirt in rain', textVi: 'Bề mặt tự làm sạch giúp cuốn trôi bụi bẩn khi trời mưa' },
      { id: 'B', text: 'Passive convective cooling without mechanical refrigeration', textVi: 'Làm mát đối lưu thụ động không cần máy lạnh cơ học' },
      { id: 'C', text: 'Hexagonal lattice structure providing earthquake resistance', textVi: 'Cấu trúc lưới lục giác mang lại khả năng chống động đất' },
    ],
    correctAnswer: 'B',
    explanationEn: 'Paragraph B describes how termite mounds use convection vents for self-cooling, inspiring the Eastgate Centre.',
    explanationVi: 'Đoạn B mô tả tổ mối dùng hệ thống thông gió đối lưu tự làm mát, tạo cảm hứng cho tòa nhà Eastgate Centre -> Chọn B.',
    evidenceQuote: 'Pearce instead drew inspiration from the self-cooling mounds built by indigenous termites.',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'summary_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành đoạn tóm tắt dưới đây. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'By emulating the lattice structure of the glass sponge, skyscraper designs can use up to twenty percent less __________ while enhancing structural durability.',
    questionTextVi: 'Bằng cách mô phỏng cấu trúc lưới của bọt biển thủy tinh, thiết kế nhà chọc trời có thể tiết kiệm tới 20% __________ trong khi vẫn gia tăng độ bền.',
    correctAnswer: 'structural steel',
    explanationEn: 'Paragraph C states: "achieving greater earthquake resilience while utilizing up to twenty percent less structural steel."',
    explanationVi: 'Đoạn C nêu: "achieving greater earthquake resilience while utilizing up to twenty percent less structural steel" -> Điền "structural steel".',
    evidenceQuote: 'achieving greater earthquake resilience while utilizing up to twenty percent less structural steel.',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'summary_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Complete the summary below. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành đoạn tóm tắt dưới đây. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'The self-cleaning property of the lotus leaf is scientifically referred to as the __________.',
    questionTextVi: 'Đặc tính tự làm sạch của lá sen được gọi theo thuật ngữ khoa học là __________.',
    correctAnswer: 'lotus effect',
    explanationEn: 'Paragraph D notes: "collecting dirt particles as they roll away—a phenomenon termed the \'lotus effect.\'"',
    explanationVi: 'Đoạn D chỉ ra: "a phenomenon termed the \'lotus effect\'" -> Điền "lotus effect".',
    evidenceQuote: 'collecting dirt particles as they roll away—a phenomenon termed the "lotus effect."',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'sentence_completion',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Complete the sentence. Choose NO MORE THAN TWO WORDS from the passage.',
    instructionVi: 'Hoàn thành câu. Chọn KHÔNG QUÁ HAI TỪ từ bài đọc.',
    questionText: 'Next-generation urban designs strive to emulate whole ecosystems, modeling closed-loop systems after mature __________.',
    questionTextVi: 'Các thiết kế đô thị thế hệ mới phấn đấu mô phỏng toàn bộ hệ sinh thái, lấy hình mẫu vòng khép kín theo các khu __________ lâu năm.',
    correctAnswer: 'forests',
    explanationEn: 'Paragraph E states: "next-generation urban developments are modeled after mature forests."',
    explanationVi: 'Đoạn E khẳng định: "next-generation urban developments are modeled after mature forests" -> Điền "forests".',
    evidenceQuote: 'next-generation urban developments are modeled after mature forests.',
  },
  {
    section: 3,
    topic: 'Biomimicry in Architecture',
    questionType: 'mcq',
    difficulty: 'medium',
    targetBand: 6.5,
    passageTitle: PASSAGE_3_TITLE,
    passageContent: PASSAGE_3_CONTENT,
    passageContentVi: PASSAGE_3_CONTENT_VI,
    instruction: 'Choose the correct letter, A, B, C, or D.',
    instructionVi: 'Chọn chữ cái đúng, A, B, C hoặc D.',
    questionText: 'How is wastewater purified in next-generation ecological architecture?',
    questionTextVi: 'Nước thải được xử lý như thế nào trong kiến trúc sinh thái thế hệ mới?',
    options: [
      { id: 'A', text: 'Through biological reed beds', textVi: 'Thông qua các bãi sậy sinh học' },
      { id: 'B', text: 'Using chemical chlorination tanks', textVi: 'Sử dụng các bể khử trùng hóa chất bằng clo' },
      { id: 'C', text: 'By boiling with excess server heat', textVi: 'Bằng cách đun sôi với nhiệt thừa từ máy chủ' },
      { id: 'D', text: 'Via synthetic silica filtering membranes', textVi: 'Qua các màng lọc silica tổng hợp' },
    ],
    correctAnswer: 'A',
    explanationEn: 'Paragraph E specifies: "wastewater from residential towers is purified through biological reed beds".',
    explanationVi: 'Đoạn E nêu rõ: "wastewater from residential towers is purified through biological reed beds" -> Chọn A.',
    evidenceQuote: 'wastewater from residential towers is purified through biological reed beds',
  },
];
